### ISSUE TITLE
Build error with clang: `clang: error: argument to '-I' is missing (expected 1 value)`

### ISSUE THREAD

**Issue by barracuda156** [pachadotdev/cpp11armadillo#9]
I got this error on CI:
```
  --->  Extracting R-cpp11armadillo
  DEBUG: Executing org.macports.extract (R-cpp11armadillo)
  --->  Extracting cpp11armadillo_0.4.0.tar.gz
  DEBUG: setting option extract.args to '/opt/local/var/macports/distfiles/R-cpp11armadillo/cpp11armadillo_0.4.0.tar.gz'
  DEBUG: Environment: 
  CC_PRINT_OPTIONS='YES'
  CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/.CC_PRINT_OPTIONS'
  CPATH='/opt/local/include'
  DEVELOPER_DIR='/Library/Developer/CommandLineTools'
  LIBRARY_PATH='/opt/local/lib'
  MACOSX_DEPLOYMENT_TARGET='13.0'
  SDKROOT='/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  SOURCE_DATE_EPOCH='1734359902'
  DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/R-cpp11armadillo/cpp11armadillo_0.4.0.tar.gz' | /usr/bin/tar -xf - 
  Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/R-cpp11armadillo/cpp11armadillo_0.4.0.tar.gz' | /usr/bin/tar -xf - 
  DEBUG: euid/egid changed to: 0/0
  DEBUG: chowned /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work to macports
  DEBUG: euid/egid changed to: 502/501
  DEBUG: Privilege de-escalation not attempted as not running as root.
  DEBUG: patch phase started at Mon Dec 16 19:35:00 UTC 2024
  DEBUG: Executing org.macports.patch (R-cpp11armadillo)
  DEBUG: Privilege de-escalation not attempted as not running as root.
  --->  Configuring R-cpp11armadillo
  DEBUG: configure phase started at Mon Dec 16 19:35:00 UTC 2024
  DEBUG: Preferred compilers: clang macports-clang-17 macports-clang-16 macports-clang-15 macports-clang-14 macports-clang-13 macports-clang-12 macports-clang-11 macports-clang-10 macports-clang-9.0
  DEBUG: Using compiler 'MacPorts Clang 16'
  DEBUG: Executing proc-pre-org.macports.configure-configure-0
  DEBUG: Active variants check for source-type install considers depends_fetch depends_extract depends_lib depends_build depends_run: R-CRAN-recommended clang-16 R
  DEBUG: Executing proc-pre-org.macports.configure-configure-1
  DEBUG: compilers.enforce_c list: 
  DEBUG: compilers.enforce_fortran list: 
  DEBUG: compilers.enforce_some_fortran list: 
  DEBUG: compilers PG: GCC version reports being UNKNOWN to MacPorts
  DEBUG: compilers PG: RPATH added to ldflags as GCC version is UNKNOWN
  DEBUG: Executing org.macports.configure (R-cpp11armadillo)
  DEBUG: Environment: 
  CC='/opt/local/bin/clang-mp-16'
  CC_PRINT_OPTIONS='YES'
  CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/.CC_PRINT_OPTIONS'
  CFLAGS='-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  CPATH='/opt/local/include'
  CPPFLAGS='-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  CXX='/opt/local/bin/clang++-mp-16'
  CXXFLAGS='-pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  DEVELOPER_DIR='/Library/Developer/CommandLineTools'
  F90FLAGS='-pipe -Os'
  FCFLAGS='-pipe -Os'
  FFLAGS='-pipe -Os'
  INSTALL='/usr/bin/install -c'
  LDFLAGS='-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  LIBRARY_PATH='/opt/local/lib'
  MACOSX_DEPLOYMENT_TARGET='13.0'
  OBJC='/opt/local/bin/clang-mp-16'
  OBJCFLAGS='-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  OBJCXX='/opt/local/bin/clang++-mp-16'
  OBJCXXFLAGS='-pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  SDKROOT='/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  SOURCE_DATE_EPOCH='1734359902'
  DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes --keep-empty-dirs 
  Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes --keep-empty-dirs 
  * checking for file ‘./DESCRIPTION’ ... OK
  * preparing ‘cpp11armadillo’:
  * checking DESCRIPTION meta-information ... OK
  * checking vignette meta-information ... OK
  * checking for LF line-endings in source and make files and shell scripts
  * checking for empty or unneeded directories
  * building ‘cpp11armadillo_0.4.0.tar.gz’
  
  DEBUG: Executing portconfigure::configure_finish
  DEBUG: Privilege de-escalation not attempted as not running as root.
  DEBUG: build phase started at Mon Dec 16 19:35:01 UTC 2024
  --->  Building R-cpp11armadillo
  DEBUG: Executing proc-pre-org.macports.build-build-0
  xinstall: mkdir /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/build
  DEBUG: Executing org.macports.build (R-cpp11armadillo)
  DEBUG: Environment: 
  CC_PRINT_OPTIONS='YES'
  CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/.CC_PRINT_OPTIONS'
  CPATH='/opt/local/include'
  DEVELOPER_DIR='/Library/Developer/CommandLineTools'
  LIBRARY_PATH='/opt/local/lib'
  MACOSX_DEPLOYMENT_TARGET='13.0'
  SDKROOT='/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  SOURCE_DATE_EPOCH='1734359902'
  DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/build --install-tests 
  Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/build --install-tests 
  * installing *source* package ‘cpp11armadillo’ ...
  ** package ‘cpp11armadillo’ successfully unpacked and MD5 sums checked
  ** using staged installation
  clang: error: argument to '-I' is missing (expected 1 value)
  Armadillo is not compatible with the C++ compiler used by R.
  ERROR: configuration failed for package ‘cpp11armadillo’
  * removing ‘/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/build/cpp11armadillo’
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/build --install-tests 
  Error: Failed to build R-cpp11armadillo: command execution failed
  DEBUG: Error code: CHILDSTATUS 38057 1
  DEBUG: Backtrace: command execution failed
      while executing
  "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
      invoked from within
  "command_exec -callback portprogress::target_progress_callback build"
      (procedure "portbuild::build_main" line 10)
      invoked from within
  "$procedure $targetname"
  Exit code: 1
  Error: See /opt/local/var/macports/logs/_Users_runner_work_macports-ports_macports-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/main.log for details.
  Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
  Error: Processing of port R-cpp11armadillo failed
  Build of 'R-cpp11armadillo' failed.
  /Users/runner/work/macports-ports/macports-ports/mpbb/mpbb: error: `install-port' failed to run successfully
```

Not sure what went wrong, previous version built fine. (This one installed locally for me, but I use gcc, not clang.)

**Comment by pachadotdev** [comment]
thanks @barracuda156 

can you tell me what you were trying to do?

I just checked my GHA workflow and it is working well

https://github.com/pachadotdev/cpp11armadillo/actions/runs/12365664895/job/34511073546

update: I added Mac 13 besides Mac 14 checks, and the check passes with Apple Clang https://github.com/pachadotdev/cpp11armadillo/actions/runs/12367293536/job/34515342718

**Comment by barracuda156** [comment]
@pachadotdev Thank you for responding!

I just wanted to update the port: https://ports.macports.org/port/R-cpp11armadillo/details
Worked fine locally for me, but failed on CI. I am not sure what went wrong, since the only change was version and checksums (we apply no patches here).

**Comment by pachadotdev** [comment]
> @pachadotdev Thank you for responding!
> 
> I just wanted to update the port: https://ports.macports.org/port/R-cpp11armadillo/details Worked fine locally for me, but failed on CI. I am not sure what went wrong, since the only change was version and checksums (we apply no patches here).

thanks @barracuda156 

do you have a link to the CI that you mention? I use Ubuntu but I can look at it

**Comment by barracuda156** [comment]
@pachadotdev Does this open? https://github.com/macports/macports-ports/actions/runs/12355451853/job/34479103526
There are a number of R ports being built there, please ignore everything else, `cpp11armadillo` build log should be clickable (“Installing R-cpp11armadillo”).

**Comment by pachadotdev** [comment]
@barracuda156 thanks!

that's more clear

is there a way you can trigger the build using my github repo instead of the CRAN version

add added some verbosity to the configure file, which shows this on my laptop

```
══ Documenting ═══════════════════════════
ℹ Updating cpp11armadillo documentation
ℹ Loading cpp11armadillo
ℹ Re-compiling cpp11armadillo (debug build)
── R CMD INSTALL ─────────────────────────
─  installing *source* package ‘cpp11armadillo’ ...
   ** using staged installation
   CXX: g++ -std=gnu++17
   R_INCLUDE_PATH: -I/usr/share/R/include
   CPP11_INCLUDE_PATH: /home/pacha/R/x86_64-pc-linux-gnu-library/4.4/cpp11/include
   PKG_CFLAGS: -I./inst/include -I/usr/share/R/include -I/home/pacha/R/x86_64-pc-linux-gnu-library/4.4/cpp11/include
   Armadillo is compatible with the C++ compiler used by R.
─  DONE (cpp11armadillo)
```

that is a new addition and it should print exactly what failed

**Comment by bastistician** [comment]
I got a possibly related configure error due to
https://github.com/pachadotdev/cpp11armadillo/blob/6ed06b531b0a7356c9673f93a670bfbe025a2e0a/configure#L6
returning "R was not built as a library" for my build of R on Linux, which does not use `--enable-R-shlib`.
`--cppflags` is for compiling against libR, which not everyone has.
I see it fails on CRAN's Fedora checks for the same reason, e.g., <https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/cpp11armadillo-00install.html>.

**Comment by pachadotdev** [comment]
> I got a possibly related configure error due to
> 
> https://github.com/pachadotdev/cpp11armadillo/blob/6ed06b531b0a7356c9673f93a670bfbe025a2e0a/configure#L6
> 
> returning "R was not built as a library" for my build of R on Linux, which does not use `--enable-R-shlib`.
> `--cppflags` is for compiling against libR, which not everyone has.
> I see it fails on CRAN's Fedora checks for the same reason, e.g., https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/cpp11armadillo-00install.html.

much appreciated !

I rushed last week to solve a minor issue. cpp11armadillo was intended (and is) header-only, and I had to include a configure file to test the compiler by CRAN request

Ultimately, this error is my fault. I should have rushed smart and not just fast.

I have just pushed a commit that solves this with a workaround (a proper one, not a hack) for the configure file.

It is amazing to read you, especially because:

1. Constructive reporting of the error.
2. Not demanding that I fix this for yesterday.
3. I have not received emails from you saying that I have errors in my code because I'm Jewish/inferior race/etc or that I do "z10n1st science" (unfortunately, the email hate is strong)

I do not say this to be bitter, but to say that I doubly appreciate the positive communication. My response to point 2 was https://pacha.dev/cpp11qpdf/articles/cpp11qpdf.html#overlaying-a-stamp-on-a-pdf and I probably made the haters buy lots of aspirin.

I also added you to NEWS.md. If anything related to this package, that I mostly made to work in a restricted server at Munk, feel free to email me to m . sepulveda [at] mail . utoronto . ca. Please add a clear subject as a I tend to read only emails with a clear subject or from people that I know, all the rest goes to trash without reading it.

**Comment by pachadotdev** [comment]
> I got a possibly related configure error due to
> 
> https://github.com/pachadotdev/cpp11armadillo/blob/6ed06b531b0a7356c9673f93a670bfbe025a2e0a/configure#L6
> 
> returning "R was not built as a library" for my build of R on Linux, which does not use `--enable-R-shlib`.
> `--cppflags` is for compiling against libR, which not everyone has.
> I see it fails on CRAN's Fedora checks for the same reason, e.g., https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/cpp11armadillo-00install.html.

much appreciated !

I rushed last week to solve a minor issue. cpp11armadillo was intended (and is) header-only, and I had to include a configure file to test the compiler by CRAN request

Ultimately, this error is my fault. I should have rushed smart and not just fast.

I have just pushed a commit that solves this with a workaround (a proper one, not a hack) for the configure file.

**Comment by bastistician** [comment]
Thanks for working on this. Note that `--ldflags` is for linking against libR, so would give "R was not built as a library" as well.

I haven't tried but *guess* you could run your configure test via `"${R_HOME}/bin/R" CMD SHLIB conftest.cpp -I"${CPP11_INCLUDE_PATH}"` (and then `rm -f conftest.*`).

Regarding the empty include path that @barracuda156 observed, I think your configure script implies that cpp11 has become a strong dependency for installing cpp11armadillo on Unix-alikes, but it is only listed in "Suggests".

**Comment by pachadotdev** [comment]
> Thanks for working on this. Note that `--ldflags` is for linking against libR, so would give "R was not built as a library" as well.
> 
> I haven't tried but _guess_ you could run your configure test via `"${R_HOME}/bin/R" CMD SHLIB conftest.cpp -I"${CPP11_INCLUDE_PATH}"` (and then `rm -f conftest.*`).
> 
> Regarding the empty include path that @barracuda156 observed, I think your configure script implies that cpp11 has become a strong dependency for installing cpp11armadillo on Unix-alikes, but it is only listed in "Suggests".

I added a simple test in the code to be able to move cpp11 to Imports without notes/warnings.

I could not replicate the "R was not built as a library" message. I will look into it and send an update to CRAN.

**Comment by pachadotdev** [comment]
@bastistician @barracuda156 I fixed it in [1d43f06](https://github.com/pachadotdev/cpp11armadillo/commit/1d43f069e1f90dd7c99c71e8ff9bb7990f122182)

please try the macbuilds again with the repo

I will send this update to CRAN

**Comment by bastistician** [comment]
I tried it now and installation still fails (for the same reason as currently seen on CRAN's Fedora check system). The current dev version still asks for the `--cppflags` and `--ldflags` config so requires R to be built as a shared library, which it is not by default on Linux. To reproduce, you need a default build of R from source with the conventional `./configure && make` steps, i.e., *without* option `--enable-R-shlib`.

> I haven't tried but *guess* you could run your configure test via `"${R_HOME}/bin/R" CMD SHLIB conftest.cpp -I"${CPP11_INCLUDE_PATH}"` (and then `rm -f conftest.*`).

I did try now. The following conftest invocation works for me:
```sh
PKG_CPPFLAGS="-I./inst/include -I\"${CPP11_INCLUDE_PATH}\"" "${R_HOME}/bin/R" CMD SHLIB conftest.cpp
```

**Comment by pachadotdev** [comment]
> I tried it now and installation still fails (for the same reason as currently seen on CRAN's Fedora check system). The current dev version still asks for the `--cppflags` and `--ldflags` config so requires R to be built as a shared library, which it is not by default on Linux. To reproduce, you need a default build of R from source with the conventional `./configure && make` steps, i.e., _without_ option `--enable-R-shlib`.
> 
> > I haven't tried but _guess_ you could run your configure test via `"${R_HOME}/bin/R" CMD SHLIB conftest.cpp -I"${CPP11_INCLUDE_PATH}"` (and then `rm -f conftest.*`).
> 
> I did try now. The following conftest invocation works for me:
> 
> ```shell
> PKG_CPPFLAGS="-I./inst/include -I\"${CPP11_INCLUDE_PATH}\"" "${R_HOME}/bin/R" CMD SHLIB conftest.cpp
> ```

thanks a lot 

I updated the configure once again, dropping cppflags and using what you told me but in a way that works with Ubuntu (implementing it as is did not pass the checks in the server here)

can you please try now?

**Comment by barracuda156** [comment]
I will try updated version today, once back to the hardware. Thank you!

**Comment by barracuda156** [comment]
Yes, it works fine now, AFAICT.

This is on macOS 13 with clang:
```
  --->  Extracting cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2.tar.gz
  DEBUG: setting option extract.args to '/opt/local/var/macports/distfiles/R-cpp11armadillo/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2.tar.gz'
  DEBUG: Environment: 
  CC_PRINT_OPTIONS='YES'
  CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/.CC_PRINT_OPTIONS'
  CPATH='/opt/local/include'
  DEVELOPER_DIR='/Library/Developer/CommandLineTools'
  LIBRARY_PATH='/opt/local/lib'
  MACOSX_DEPLOYMENT_TARGET='13.0'
  SDKROOT='/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  SOURCE_DATE_EPOCH='1734523049'
  DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/R-cpp11armadillo/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2.tar.gz' | /usr/bin/tar -xf - 
  Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/R-cpp11armadillo/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2.tar.gz' | /usr/bin/tar -xf - 
  DEBUG: euid/egid changed to: 0/0
  DEBUG: chowned /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work to macports
  DEBUG: euid/egid changed to: 502/501
  DEBUG: Privilege de-escalation not attempted as not running as root.
  DEBUG: patch phase started at Wed Dec 18 12:03:20 UTC 2024
  DEBUG: Executing org.macports.patch (R-cpp11armadillo)
  DEBUG: Privilege de-escalation not attempted as not running as root.
  DEBUG: configure phase started at Wed Dec 18 12:03:20 UTC 2024
  --->  Configuring R-cpp11armadillo
  DEBUG: Preferred compilers: clang macports-clang-17 macports-clang-16 macports-clang-15 macports-clang-14 macports-clang-13 macports-clang-12 macports-clang-11 macports-clang-10 macports-clang-9.0
  DEBUG: Using compiler 'MacPorts Clang 16'
  DEBUG: Executing proc-pre-org.macports.configure-configure-0
  DEBUG: Active variants check for source-type install considers depends_fetch depends_extract depends_lib depends_build depends_run: R-cpp11 R-CRAN-recommended clang-16 R
  DEBUG: Executing proc-pre-org.macports.configure-configure-1
  DEBUG: compilers.enforce_c list: 
  DEBUG: compilers.enforce_fortran list: 
  DEBUG: compilers.enforce_some_fortran list: 
  DEBUG: compilers PG: GCC version reports being UNKNOWN to MacPorts
  DEBUG: compilers PG: RPATH added to ldflags as GCC version is UNKNOWN
  DEBUG: Executing org.macports.configure (R-cpp11armadillo)
  DEBUG: Environment: 
  CC='/opt/local/bin/clang-mp-16'
  CC_PRINT_OPTIONS='YES'
  CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/.CC_PRINT_OPTIONS'
  CFLAGS='-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  CPATH='/opt/local/include'
  CPPFLAGS='-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  CXX='/opt/local/bin/clang++-mp-16'
  CXXFLAGS='-pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  DEVELOPER_DIR='/Library/Developer/CommandLineTools'
  F90FLAGS='-pipe -Os'
  FCFLAGS='-pipe -Os'
  FFLAGS='-pipe -Os'
  INSTALL='/usr/bin/install -c'
  LDFLAGS='-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  LIBRARY_PATH='/opt/local/lib'
  MACOSX_DEPLOYMENT_TARGET='13.0'
  OBJC='/opt/local/bin/clang-mp-16'
  OBJCFLAGS='-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  OBJCXX='/opt/local/bin/clang++-mp-16'
  OBJCXXFLAGS='-pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  SDKROOT='/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  SOURCE_DATE_EPOCH='1734523049'
  DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes --keep-empty-dirs 
  Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes --keep-empty-dirs 
  * checking for file ‘./DESCRIPTION’ ... OK
  * preparing ‘cpp11armadillo’:
  * checking DESCRIPTION meta-information ... OK
  * checking for LF line-endings in source and make files and shell scripts
  * checking for empty or unneeded directories
  * building ‘cpp11armadillo_0.4.1.tar.gz’
  
  DEBUG: Executing portconfigure::configure_finish
  DEBUG: Privilege de-escalation not attempted as not running as root.
  DEBUG: build phase started at Wed Dec 18 12:03:22 UTC 2024
  --->  Building R-cpp11armadillo
  DEBUG: Executing proc-pre-org.macports.build-build-0
  xinstall: mkdir /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/build
  DEBUG: Executing org.macports.build (R-cpp11armadillo)
  DEBUG: Environment: 
  CC_PRINT_OPTIONS='YES'
  CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/.CC_PRINT_OPTIONS'
  CPATH='/opt/local/include'
  DEVELOPER_DIR='/Library/Developer/CommandLineTools'
  LIBRARY_PATH='/opt/local/lib'
  MACOSX_DEPLOYMENT_TARGET='13.0'
  SDKROOT='/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
  SOURCE_DATE_EPOCH='1734523049'
  Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/build --install-tests 
  DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_R_R-cpp11armadillo/R-cpp11armadillo/work/build --install-tests 
  * installing *source* package ‘cpp11armadillo’ ...
  ** using staged installation
  ==================================
   Compiler Configuration Variables 
   
  CPP11_INCLUDE_PATH: /opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/cpp11/include
  INST_INCLUDE_PATH: ./inst/include
  PKG_CPPFLAGS: -I./inst/include -I/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/cpp11/include
  ===================================
   Testing minimal Armadillo example 
   
  using C++ compiler: ‘clang version 16.0.6’
  using SDK: ‘MacOSX13.3.sdk’
  /opt/local/bin/clang++-mp-16 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./inst/include -I/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/cpp11/include  -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk    -fPIC  -pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64   -c conftest.cpp -o conftest.o
  /opt/local/bin/clang++-mp-16 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/opt/local/Library/Frameworks/R.framework/Resources/lib -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64 -o conftest.so conftest.o -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
  Armadillo is compatible with the C++ compiler used by R.
  ** R
  ** inst
  ** tests
  ** byte-compile and prepare package for lazy loading
  ** help
  *** installing help indices
  *** copying figures
  ** building package indices
  ** installing vignettes
  ** testing if installed package can be loaded from temporary location
  ** testing if installed package can be loaded from final location
  ** testing if installed package keeps a record of temporary installation path
  * DONE (cpp11armadillo)
```

**Comment by barracuda156** [comment]
And on 10.6 with gcc:
```
:notice:configure --->  Configuring R-cpp11armadillo
:debug:configure Preferred compilers: macports-gcc-14 macports-gcc-13 macports-gcc-12 macports-gcc-11 macports-gcc-10 macports-gcc-7 macports-gcc-6 macports-gcc-5 macports-clang-11 macports-clang-10 macports-clang-9.0 macports-clang-8.0 macports-clang-7.0 macports-clang-6.0 macports-clang-5.0
:debug:configure Using compiler 'MacPorts GCC 13'
:debug:configure Executing proc-pre-org.macports.configure-configure-0
:debug:configure Active variants check for source-type install considers depends_fetch depends_extract depends_lib depends_build depends_run: R-cpp11 libgcc libgcc13 R-CRAN-recommended gcc13 R
:debug:configure Executing proc-pre-org.macports.configure-configure-1
:debug:configure compilers.enforce_c list: 
:debug:configure compilers.enforce_fortran list: 
:debug:configure compilers.enforce_some_fortran list: 
:debug:configure compilers PG: GCC version reports being UNKNOWN to MacPorts
:debug:configure compilers PG: RPATH added to ldflags as GCC version is UNKNOWN
:debug:configure Executing org.macports.configure (R-cpp11armadillo)
:debug:configure Environment: 
:debug:configure CC='/opt/local/bin/gcc-mp-13'
:debug:configure CC_PRINT_OPTIONS='YES'
:debug:configure CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-cpp11armadillo/R-cpp11armadillo/work/.CC_PRINT_OPTIONS'
:debug:configure CFLAGS='-pipe -Os'
:debug:configure CPATH='/opt/local/include'
:debug:configure CPPFLAGS='-I/opt/local/include'
:debug:configure CXX='/opt/local/bin/g++-mp-13'
:debug:configure CXXFLAGS='-pipe -Os -D_GLIBCXX_USE_CXX11_ABI=0'
:debug:configure DEVELOPER_DIR='/Developer'
:debug:configure DYLD_LIBRARY_PATH='/opt/local/lib/libgcc'
:debug:configure F77='/opt/local/bin/gfortran-mp-13'
:debug:configure F90='/opt/local/bin/gfortran-mp-13'
:debug:configure F90FLAGS='-pipe -Os'
:debug:configure FC='/opt/local/bin/gfortran-mp-13'
:debug:configure FCFLAGS='-pipe -Os'
:debug:configure FFLAGS='-pipe -Os'
:debug:configure INSTALL='/usr/bin/install -c'
:debug:configure LDFLAGS='-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc'
:debug:configure LIBRARY_PATH='/opt/local/lib'
:debug:configure MACOSX_DEPLOYMENT_TARGET='10.6'
:debug:configure OBJC='/opt/local/bin/gcc-mp-13'
:debug:configure OBJCFLAGS='-pipe -Os'
:debug:configure OBJCXX='/opt/local/bin/g++-mp-13'
:debug:configure OBJCXXFLAGS='-pipe -Os -D_GLIBCXX_USE_CXX11_ABI=0'
:debug:configure SOURCE_DATE_EPOCH='1734522772'
:info:configure Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes --keep-empty-dirs 
:debug:configure system:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes --keep-empty-dirs 
:info:configure * checking for file ‘./DESCRIPTION’ ... OK
:info:configure * preparing ‘cpp11armadillo’:
:info:configure * checking DESCRIPTION meta-information ... OK
:info:configure * checking for LF line-endings in source and make files and shell scripts
:info:configure * checking for empty or unneeded directories
:info:configure * building ‘cpp11armadillo_0.4.1.tar.gz’
:debug:configure Executing portconfigure::configure_finish
:debug:build build phase started at Wed Dec 18 19:53:12 CST 2024
:notice:build --->  Building R-cpp11armadillo
:debug:build Executing proc-pre-org.macports.build-build-0
:info:build xinstall: mkdir /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-cpp11armadillo/R-cpp11armadillo/work/build
:debug:build Executing org.macports.build (R-cpp11armadillo)
:debug:build Environment: 
:debug:build CC_PRINT_OPTIONS='YES'
:debug:build CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-cpp11armadillo/R-cpp11armadillo/work/.CC_PRINT_OPTIONS'
:debug:build CPATH='/opt/local/include'
:debug:build DEVELOPER_DIR='/Developer'
:debug:build DYLD_LIBRARY_PATH='/opt/local/lib/libgcc'
:debug:build LIBRARY_PATH='/opt/local/lib'
:debug:build MACOSX_DEPLOYMENT_TARGET='10.6'
:debug:build SOURCE_DATE_EPOCH='1734522772'
:info:build Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-cpp11armadillo/R-cpp11armadillo/work/build --install-tests 
:debug:build system:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-cpp11armadillo/R-cpp11armadillo/work/cpp11armadillo-4a1a432c13ae81370b26200f4c3c8cdaa1986de2" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-cpp11armadillo/R-cpp11armadillo/work/build --install-tests 
:info:build * installing *source* package ‘cpp11armadillo’ ...
:info:build ** using staged installation
:info:build ==================================
:info:build  Compiler Configuration Variables 
:info:build  
:info:build CPP11_INCLUDE_PATH: /opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/cpp11/include
:info:build INST_INCLUDE_PATH: ./inst/include
:info:build PKG_CPPFLAGS: -I./inst/include -I/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/cpp11/include
:info:build ===================================
:info:build  Testing minimal Armadillo example 
:info:build  
:info:build using C++ compiler: ‘g++-mp-13 (MacPorts gcc13 13.3.0_2+stdlib_flag) 13.3.0’
:info:build using SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
:info:build /opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./inst/include -I/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/cpp11/include  -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -arch ppc   -c conftest.cpp -o conftest.o
:info:build /opt/local/bin/g++-mp-13 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -Wl,-rpath,/opt/local/lib/libgcc -arch ppc -o conftest.so conftest.o -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
:info:build Warning message:
:info:build In system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
:info:build   running command ''xcrun' --show-sdk-path 2>&1' had status 64
:info:build Armadillo is compatible with the C++ compiler used by R.
:info:build ** R
:info:build ** inst
:info:build ** tests
:info:build ** byte-compile and prepare package for lazy loading
:info:build ** help
:info:build *** installing help indices
:info:build *** copying figures
:info:build ** building package indices
:info:build ** installing vignettes
:info:build ** testing if installed package can be loaded from temporary location
:info:build ** testing if installed package can be loaded from final location
:info:build ** testing if installed package keeps a record of temporary installation path
:info:build * DONE (cpp11armadillo)
```

**Comment by pachadotdev** [comment]
thanks a lot @barracuda156 !!!
and also to @bastistician
